name: Emerge Tools

on:
  push:
    branches:
      - master

jobs:
  emerge_tools:
    name: Upload Build Analysis to Emerge Tools

    runs-on: ubuntu-latest

    env:
      EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_TOKEN }}
      HEAD_SHA: ${{ env.GITHUB_SHA }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Create local properties
        run: touch ./local.properties
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Emerge Upload
        run: ./gradlew emergeUploadReleaseAab